# accelerrate_config.yaml
compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU #MULTI_GPU MULTI_CPU DEEPSPEED
deepspeed_config:
  zero3_init_flag: true
  deepspeed_config_file: ./ds_config_zero2.json
#downcast_bf16: 'fp16'
gpu_ids: all
machine_rank: 0
main_process_ip: 127.0.0.1 # 主机ip
#main_process_port: 10086  # 端口
main_training_function: main
#mixed_precision: 'fp16' # bf16 no等
num_machines: 1  # 这个后面可以再配置启动命令中修改
num_processes: 1 # 这个指示的的是多机多卡的总卡数，而不是每台机器卡数，类似于ddp的rank
rdzv_backend: static
same_network: True
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false